### ISSUE TITLE
Server error with JSON, 6.2, recent patches and large pools

### ISSUE THREAD

**Issue by julien-f** [julien-f/js-xen-api#2]
XAPI returns a `500 Server Error` on large pools when using embedded JSON in XML-RPC with Xen-Server 6.2, recent patches (XS62ESP 1011, 1013, 1014 or 1025).

**Comment by jonludlam** [comment]
Anything interesting in the logs server-side?

**Comment by olivierlambert** [comment]
Nothing special (IIRC), but I'll try to install a XS 6.2 as a VM in our lab to make some tests. But it will be probably hard to reproduce since it seems happening with large pools.

**Comment by olivierlambert** [comment]
@jonludlam : if you got any chance to have a large pool on 6.2 with the given patches, it should be very trivial to reproduce with any Xen Orchestra instance (XOA or from the sources)

**Comment by olivierlambert** [comment]
The problem is also present on a 6.1 host, also on a large pool.

Detail about the error returned:
```
XML-RPC Error: Unknown XML-RPC tag 'H1' (response status undefined)

<html>
  <body>
    <h1>HTTP 500 internal server error</h1>
    An unexpected error occurred; please wait a while and try again. If the problem persists, please contact your support representative.
    <h1> Additional information </h1>
    Invalid_argument(&quot;String.create&quot
  </body>
</html>
```

However, we successfully connected to this XAPI seconds ago:

```
14:10:48 GMT xen-api root@xxxxxx: session.login_with_password(...) [176ms] ==> string
14:10:48 GMT xen-api root@xxxxxx: connected
```

But, 6 seconds after that, without anything before, we got:

```
14:10:54 GMT xen-api root@xxxxxx: event.from(...) [6s] =!> Error: Unknown XML-RPC tag 'H1'
```

**Comment by jonludlam** [comment]
Hmm. I'm going to guess that we're hitting the 16Mb limit on string for the 32 bit dom0. We fixed this for the XML by switching to streaming the response rather than constructing it in a string and sending it out. I would therefore expect the problem not to exist on XS 6.5 and newer (with 64 bit dom0)

**Comment by olivierlambert** [comment]
@jonludlam: makes sense. I suppose there is nothing that can be done for this?

**Comment by jonludlam** [comment]
You're welcome to submit a pull request :-)

It's not terribly easy because the json is embedded into the Xml [here](https://github.com/xenserver/xen-api/blob/clearwater-sp1-bugfix/ocaml/xapi/api_server.ml#L142)
```ocaml
let translated =
      match is_json,response with
        true,XMLRPC.Success [Xml.Element("value",_,[x])] -> XMLRPC.Success [Xml.Element("value",[],[Xml.PCData (Json.xmlrpc_to_json x)])]
      | _ -> response
    in
```
where you can see it matches a successful response, and turns it into a successful response with an embedded string in it - the 'PCData' bit. The problem is that the data type for PCData is a string, as seen [here](https://github.com/xenserver/xen-api-libs/blob/clearwater-sp1-bugfix/xml-light2/xml.ml#L23)

```ocaml
type xml =
	| Element of (string * (string * string) list * xml list)
	| PCData of string
```

So that would need to be fixed too. So it requires that datatype to become a bigbuffer, the rest of the module fixing up as a result, and [Json.xmlrpc_to_json](https://github.com/xenserver/xen-api/blob/clearwater-sp1-bugfix/ocaml/idl/ocaml_backend/json.ml) to return a bigbuffer. Not trivial, but not too bad either.

**Comment by olivierlambert** [comment]
Ouch ^^ Not trivial for us, but that's not my main concern. Imagine if we do a perfect PR fixing this, is there any chance that it will be backported as a hotfix for 6.1/6.2 versions?
